### ISSUE TITLE
Request: Delaque Gang

### ISSUE THREAD

**Issue by tw6464** [BSData/necromunda-gang-war#46]
Now that the two compilation books are out, i think now is a good time as any to get the House Delaque Gang all completed

**Comment by tw6464** [comment]
So... I would like to get this done, but I am unsure how to proceed with the desktop version of this repository. Specifically, I've cloned the main repository but its not showing up in the desktop version of this app.

**Comment by tw6464** [comment]
I would like to get some help with this, as I am totally lost on how to make these entries work; I read through the instructions and I still have no clue what im doing

**Comment by tw6464** [comment]
alright. I'll admit it. I had no idea what I was doing when I asked to join. I still have no idea what I'm doing. Which is why it would be grateful if i got some help to get this done because frankly, the fact that it's taken this long to update this repository is absurd.

**Comment by amis92** [comment]
@tw6464 I think asking around on https://gitter.im/BSData/wh40k will yield the fastest answer. :)

**Comment by tw6464** [comment]
@amis92 I have asked... hopefully i get a positive response

**Comment by Stormxlr** [comment]
Hi, I'm also new to this but would love to provide any help I can

**Comment by sizeablerainbow** [comment]
currently trying to add this slowly adding weapons and traits and that but unable to check if working as my index.bsi will not work correctly in manage data getting error 
first time trying to work with this program so dont understand a lot but would like to help 

Details:

Could not import data from index because the data index url is invalid

1) net.battlescribe.model.dataindex.DataIndex@577c3959: Could not import data from index because the data index url is invalid
	at net.battlescribe.a.a.c(BattleScribe:1780)
	at net.battlescribe.a.a.a(BattleScribe:1510)
	at net.battlescribe.a.a.a(BattleScribe:1492)
	at net.battlescribe.desktop.common.BattleScribeFrame$7.a(BattleScribe:471)
	at net.battlescribe.desktop.common.BattleScribeFrame$7.doInBackground(BattleScribe:466)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by andresbenitezc** [comment]
I forked the repo and added Delaque to the bs files.. I am unsure if I did it correctly, what I did was to make a copy of the Escher gang and change the names, gang weapons, and weapon costs then went into the .gsc file and added the missing weapons. I don't know if this is still being actively maintained but if anyone can proofread my work that would be great.
